# Generated by Django 5.0 on 2024-01-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_delete_appoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('specialisation', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
            ],
        ),
    ]
