# Generated by Django 5.0.1 on 2024-01-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortable',
            name='dept_id',
        ),
        migrations.DeleteModel(
            name='DepartmentTable',
        ),
        migrations.DeleteModel(
            name='DoctorTable',
        ),
    ]
