# Generated by Django 5.0 on 2024-01-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_table',
        ),
    ]
