# Generated by Django 5.0 on 2024-01-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_doctor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttable',
            name='dept_pic',
            field=models.FileField(blank=True, default='g1.jpg', null=True, upload_to='dept_pics'),
        ),
    ]
